# brainboost_data_source_package/data_source_addons/__init__.py
from brainboost_data_source_package.data_source_addons.BBKnowledgeHookRealTimeDataSource import BBKnowledgeHookRealTimeDataSource
from .BBGitHubDataSource import BBGitHubDataSource
from .BBGitLabDataSource import BBGitLabDataSource
# Add similar lines for other data sources as needed
